### ISSUE TITLE
代码运行问题

### ISSUE THREAD

**Issue by chenshen03** [Luoyadan/Zero-shot-Hashing#1]
您好，请问下能否提供下代码中所对应数据集的下载链接？

另外在test.m代码里有引用到utils文件夹，但是源代码里并没有存在该文件夹。

**Comment by chenshen03** [comment]
已解决

**Comment by huangmeixue** [comment]
您好，我也遇到了这两个问题，请问您是怎么解决的？

**Comment by chenshen03** [comment]
@huangmeixue utils文件夹貌似没什么作用，对应代码那行可以删掉。然后我按照论文的说明生成了数据集（基于CNN的特征以及利用google预训练的word2vec生成word embededing数据），你可以自己试试。

**Comment by huangmeixue** [comment]
@chenshen03 好滴，非常感谢你~
还想请问下代码里cifar_10_norm_embedded_zeroshot数据集的字段格式是什么呢？

**Comment by chenshen03** [comment]
> @chenshen03 好滴，非常感谢你~
> 还想请问下代码里cifar_10_norm_embedded_zeroshot数据集的字段格式是什么呢？

这个代码我很早前跑的，我看了下我保存数据的格式，大体如下：
![image](https://user-images.githubusercontent.com/20432947/71774692-4b28c700-2fae-11ea-9c3f-4cc2b429e261.png)
